<?php

namespace Container5EnDjFX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMesaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MesaController' shared autowired service.
     *
     * @return \App\Controller\MesaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MesaController.php';

        $container->services['App\\Controller\\MesaController'] = $instance = new \App\Controller\MesaController(($container->privates['App\\Repository\\MesaRepository'] ?? $container->load('getMesaRepositoryService')), ($container->privates['App\\Repository\\CategoriaRepository'] ?? $container->load('getCategoriaRepositoryService')), ($container->privates['App\\Repository\\ProductoRepository'] ?? $container->load('getProductoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\MesaController', $container));

        return $instance;
    }
}
