<?php

namespace Container5EnDjFX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPedidoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\PedidoController' shared autowired service.
     *
     * @return \App\Controller\PedidoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/PedidoController.php';

        $container->services['App\\Controller\\PedidoController'] = $instance = new \App\Controller\PedidoController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\MesaRepository'] ?? $container->load('getMesaRepositoryService')), ($container->privates['App\\Repository\\ProductoRepository'] ?? $container->load('getProductoRepositoryService')), ($container->privates['App\\Repository\\PedidoRepository'] ?? $container->load('getPedidoRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\PedidoController', $container));

        return $instance;
    }
}
