<?php

namespace ContainerZZhpIxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fz1Sfi3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fz1Sfi3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fz1Sfi3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mesaRepository' => ['privates', '.errored.wlF5.hi', NULL, 'Cannot determine controller argument for "App\\Controller\\MesaController::menuMesa()": the $mesaRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MesaRepository".'],
        ], [
            'mesaRepository' => '?',
        ]);
    }
}
