<?php

namespace ContainerZZhpIxd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_WlF5_HiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.wlF5.hi' shared service.
     *
     * @return \App\Repository\MesaRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\MesaController::menuMesa()": the $mesaRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MesaRepository".');
    }
}
