<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKlxPEhy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKlxPEhy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKlxPEhy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKlxPEhy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKlxPEhy\App_KernelDevDebugContainer([
    'container.build_hash' => 'KlxPEhy',
    'container.build_id' => '894948e4',
    'container.build_time' => 1769600890,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKlxPEhy');
