<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKZUoDrw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKZUoDrw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKZUoDrw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKZUoDrw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKZUoDrw\App_KernelDevDebugContainer([
    'container.build_hash' => 'KZUoDrw',
    'container.build_id' => '419f46a7',
    'container.build_time' => 1769605362,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKZUoDrw');
