<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerClVs79W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerClVs79W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerClVs79W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerClVs79W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerClVs79W\App_KernelDevDebugContainer([
    'container.build_hash' => 'ClVs79W',
    'container.build_id' => 'df59709a',
    'container.build_time' => 1769685341,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerClVs79W');
