<?php

namespace Container6X5TfvK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCocinaControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CocinaController' shared autowired service.
     *
     * @return \App\Controller\CocinaController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CocinaController.php';

        $container->services['App\\Controller\\CocinaController'] = $instance = new \App\Controller\CocinaController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\CocinaController', $container));

        return $instance;
    }
}
