<?php

namespace ContainerKZUoDrw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMesaControllermenuMesaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pJdVZQY.App\Controller\MesaController::menuMesa()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pJdVZQY.App\\Controller\\MesaController::menuMesa()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mesaRepository' => ['privates', 'App\\Repository\\MesaRepository', 'getMesaRepositoryService', true],
        ], [
            'mesaRepository' => 'App\\Repository\\MesaRepository',
        ]))->withContext('App\\Controller\\MesaController::menuMesa()', $container);
    }
}
